name: stream_feed
description: Stream Feed official Dart SDK. Build your own feed experience using
  Dart and Flutter.
version: 0.7.0+1
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
environment:
  sdk: ">=3.0.0 <4.0.0"

publish_to: none

dependencies:
  collection: ^1.15.0
  dio: ^5.0.0
  equatable: ^2.0.0
#  faye_dart:
#    path: ../faye_dart
  http_parser: ^4.0.0
  intl: ^0.18.1
  jose: ^0.3.4
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.3.0
  mime: ^1.0.4

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  mocktail: ^1.0.0
  test: ^1.25.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
